### ISSUE TITLE
Issue while running yarn start after yarn build

### ISSUE THREAD

**Issue by neeteshraj** [mikemajesty/nestjs-microservice-boilerplate-api#12]
{"stack":"AggregateError\n    at internalConnectMultiple (node:net:1114:18)\n    at afterConnectMultiple (node:net:1667:5)\n    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)","errors":"Error: connect ECONNREFUSED ::1:4318,Error: connect ECONNREFUSED 127.0.0.1:4318","code":"ECONNREFUSED","name":"AggregateError"}
{"stack":"Error: PeriodicExportingMetricReader: metrics export failed (error AggregateError)\n    at doExport (/Users/niteshrajkhanal/Desktop/nestjs-microservice-boilerplate-api/node_modules/@opentelemetry/sdk-metrics/build/src/export/PeriodicExportingMetricReader.js:76:23)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async PeriodicExportingMetricReader._doRun (/Users/niteshrajkhanal/Desktop/nestjs-microservice-boilerplate-api/node_modules/@opentelemetry/sdk-metrics/build/src/export/PeriodicExportingMetricReader.js:84:13)\n    at async PeriodicExportingMetricReader._runOnce (/Users/niteshrajkhanal/Desktop/nestjs-microservice-boilerplate-api/node_modules/@opentelemetry/sdk-metrics/build/src/export/PeriodicExportingMetricReader.js:55:13)","message":"PeriodicExportingMetricReader: metrics export failed (error AggregateError)","name":"Error"}

**Comment by neeteshraj** [comment]
After building the project and trying to start the application. The application starts but it gives this error in the end.

**Comment by neeteshraj** [comment]
<img width="1440" alt="Screenshot 2024-02-02 at 2 41 35 PM" src="https://github.com/mikemajesty/nestjs-microservice-boilerplate-api/assets/37995777/24906076-38cd-4d6d-a173-92522509fb55">
